Repository Psyhackological/AAA, pull requests merged in 2022-07, with the labels that each got.

#40 Add official site to PixaPencil
  README.md
Labels: documentation, good_first_contribution

#39 More apps added
  README.md
Labels: typo, new_app

#53 Cleaner navigation using TOC
  README.md
Labels: documentation

#55 All in one apps
  README.md
Labels: new_app, good_first_contribution

#57 Replace QR app
  README.md
Labels: documentation, good_first_contribution, violates_rules
