Repository Psyhackological/AAA, pull requests merged in 2022-06, with the labels that each got.

#1 Added Simon Tatham's Puzzles under Games
  README.md
Labels: question

#4 Add GrapheneOS Google Play links
  README.md
Labels: documentation, good first issue

#9 Added some more apps
  README.md
Labels: enhancement, violates_rules, question

#12 Added new apps
  README.md
Labels: enhancement, good_first_contribution, question

#16 Add some apps
  README.md
Labels: new_app, good_first_contribution, question

#15 Add two apps
  README.md
Labels: new_app, good_first_contribution

#13 Add some new apps
  README.md
Labels: new_app, good_first_contribution, question

#20 Added more apps!
  README.md
Labels: documentation, new_app, question

#28 Add Pluvia Weather
  README.md
Labels: new_app, good_first_contribution

#27 More apps!
  README.md
Labels: new_app, help_wanted
