Repository Psyhackological/AAA, pull requests merged in 2023-03, with the labels that each got.

#67 Add some apps, update icons and sort in alphabetical order
  PRIVACY.md
  README.md
Labels: documentation, new_app, good_first_contribution

#68 Add Kvaesitso
  README.md
Labels: new_app, good_first_contribution

#69 Fix icon links
  README.md
Labels: documentation, good_first_contribution
