Repository Psyhackological/AAA, pull requests merged in 2025-05, with the labels that each got.

#93 Replace Aluicord with Revenge
  README.md
Labels: documentation, new_app, good_first_contribution

#94 Added Proton Mail
  README.md
Labels: new_app

#95 Added Fcitx5 for Android
  README.md
Labels: new_app, good_first_contribution
